name: Deployment
on: workflow_dispatch

jobs:
  test:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
      - name: Install helm
        uses: azure/setup-helm@v1
      - name: Save kubeconfig
        run: echo $KUBECONFIG_DATA > /tmp/kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      - name: Deploy nginx-ingress
        run: ./deploy_nginx_ingress.sh
        env:
          DEPLOY_NGINX_INGRESS: ${{ secrets.DEPLOY_NGINX_INGRESS }}
          KUBECONFIG: /tmp/kubeconfig
      - name: Deploy cert-manager
        run: ./deploy_cert_manager.sh
        env:
          DEPLOY_CERT_MANAGER: ${{ secrets.DEPLOY_CERT_MANAGER }}
          KUBECONFIG: /tmp/kubeconfig
      - name: Deploy MySQL
        run: ./deploy_mysql.sh
        env:
          DEPLOY_MYSQL: ${{ secrets.DEPLOY_MYSQL }}
          KUBECONFIG: /tmp/kubeconfig
