---
name: Deployment
on:
  workflow_dispatch:
    inputs:
      deploy_nginx_ingress:
        description: "Deploy nginx-ingress"
        required: false
        default: ""
      deploy_cert_manager:
        description: "Deploy cert-manager"
        required: false
        default: ""
      deploy_mysql:
        description: "Deploy MySQL"
        required: false
        default: ""
      deploy_redis:
        description: "Deploy Redis"
        required: false
        default: ""
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    name: Test
    uses: ./.github/workflows/reusable_test.yaml
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Done as a variable because it doesn't work in place.

      - name: Install Helm
        uses: azure/setup-helm@v2.0

      - name: Deploy nginx-ingress
        run: scripts/deploy_nginx_ingress.sh
        if: ${{ github.event.inputs.deploy_nginx_ingress }}

      - name: Deploy cert-manager
        run: scripts/deploy_cert_manager.sh
        env:
          EMAIL: ${{ secrets.EMAIL }}
        if: ${{ github.event.inputs.deploy_cert_manager }}

      - name: Deploy MySQL
        run: scripts/deploy_mysql.sh
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        if: ${{ github.event.inputs.deploy_mysql }}

      - name: Deploy Redis
        run: scripts/deploy_redis.sh
        if: ${{ github.event.inputs.deploy_redis }}
